replicaCount: 2

image:
  repository: 417521971848.dkr.ecr.us-east-1.amazonaws.com/frontend
  tag: "1.1.0"
  pullPolicy: IfNotPresent

imagePullSecrets:
  - name: ecr-registry-secret

environment:
  name: staging

ingress:
  enabled: false
