replicaCount: 1

image:
  repository: 417521971848.dkr.ecr.us-east-1.amazonaws.com/order-service
  tag: "07eda39"
  pullPolicy: IfNotPresent

imagePullSecrets:
  - name: ecr-registry-secret

environment:
  name: staging

service:
  type: ClusterIP
  port: 8082

ingress:
  enabled: false
